services:
  - type: web
    name: time-series-analysis
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run time.py
    pythonVersion: 3.11  # Recommended version, adjust if needed
