services:
  - type: web
    name: time-series-analysis
    env: python
    pythonVersion: 3.10
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run time.py --server.port $PORT
    envVars:
      - key: PORT
        value: "10000"
